# Generated by Django 4.1.5 on 2023-01-09 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eCommerceApp', '0004_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('feedBACK', models.TextField(blank=True, null=True)),
                ('createdDate', models.DateField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProducTFeedbackProductRelatedName', to='eCommerceApp.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductFeedbackUserRelatedName', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='productfeedback',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='add_to_cart_once'),
        ),
    ]
