# Generated by Django 4.1.5 on 2023-01-09 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eCommerceApp', '0005_productfeedback_productfeedback_add_to_cart_once'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(blank=True, max_length=250, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Quantity', models.IntegerField()),
                ('PostOffice', models.CharField(blank=True, max_length=250, null=True)),
                ('Thana', models.CharField(blank=True, max_length=250, null=True)),
                ('District', models.CharField(blank=True, max_length=250, null=True)),
                ('Zipcode', models.CharField(blank=True, max_length=250, null=True)),
                ('Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProductorderProductRelatedName', to='eCommerceApp.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductOrderUserRelatedName', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
