# Generated by Django 4.1.5 on 2023-01-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerceApp', '0006_productorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='0_uploads/order_product_image'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='Price',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='Title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='TotalPrice',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
