# Generated by Django 4.1.5 on 2023-01-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerceApp', '0007_productorder_image_productorder_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='Quantity',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
