# Generated by Django 4.1.5 on 2023-01-10 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eCommerceApp', '0008_alter_productorder_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProductOrderProductRelatedName', to='eCommerceApp.products'),
        ),
        migrations.CreateModel(
            name='ShopingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateField(auto_now=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ShoppingCartRelatedName', to='eCommerceApp.products')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserShoppingCartRelatedName', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='shopingcart',
            constraint=models.UniqueConstraint(fields=('User', 'Product'), name='review_once'),
        ),
    ]
