# Generated by Django 4.1.5 on 2023-01-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerceApp', '0009_alter_productorder_product_shopingcart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='OrderStatus',
            field=models.CharField(blank=True, choices=[('Processing', 'Processing'), ('Shipped', 'Shipped'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], max_length=30, null=True),
        ),
    ]
