# Generated by Django 4.1.5 on 2023-01-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerceApp', '0010_productorder_orderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='createdDate',
            field=models.DateField(auto_now=True),
        ),
    ]
